### ISSUE TITLE
where is the Build.PL

### ISSUE THREAD

**Issue by abayega** [bioperl/Bio-FeatureIO#11]
I am a newbee. I have failed to install Bio-FeatureIO on Ubuntu 16 LTS following;

sudo cpan
install CPAN
reload cpan
install Bio::FeatureIO::gff

even trying to download the source code has failed since I cannot find the Build.PL file
Thanks

**Comment by hdevillers** [comment]
Hi, I got the same problem, hence, I make my own Build.PL. Note that you must had two depedencies:
Config::Any and Bio::GFF3::LowLevel in addition to dependencies given in the README.

Here is my (minimal) Build.PL
`use strict;
use warnings;
use Module::Build;

my $builder = Module::Build->new(
  module_name        => 'Bio::FeatureIO',
  licence            => 'perl',
  dist_author        => 'Chris Fields and Allen Day',
  dist_abstract      => 'Bio::FeatureIO is a BioPerl-based parser for feature da
ta from common biological sequence formats, such as GFF3, GTF, and BED.',
  dist_version_from  => 'lib/Bio/FeatureIO.pm',
  requires           => {
    'URI::Escape' => 0,
    'XML::DOM::XPath' => 0,
    'Config::Any' => 0,
    'Bio::GFF3::LowLevel' => 0
  },
  meta_merge => {
    ressources => {
      repository => 'https://github.com/bioperl/Bio-FeatureIO'
    }
 },
 create_makefile_pl => 'traditional',
 installdir         => 'vendor'
);
`

Then, to build and install it : 
perl Build.PL
./Build manifest
./Build
./Build test # I obtained no failed test
./Build install # Possibly require root rights...

**Comment by cjfields** [comment]
We use [Dist::Zilla](http://dzil.org) instead of Module::Build (note the `dist.ini` file), and only support installation of the code from CPAN.
